# Generated by Django 4.1 on 2022-08-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jab_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('part Time', 'part Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
