# Generated by Django 4.1 on 2022-08-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='id',
        ),
        migrations.AddField(
            model_name='apply',
            name='number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
