# Generated by Django 4.1 on 2022-08-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_apply_id_apply_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='number',
        ),
        migrations.AddField(
            model_name='apply',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
