# Generated by Django 4.1 on 2022-08-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jab_type',
            new_name='job_type',
        ),
    ]
